name: valorant_strategies_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: valorantfonts
      fonts:
        - asset: assets/fonts/Valorant-Font.ttf

